name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  IMAGE_REPOSITORY: anqa-interface

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: user/app:latest # doens't matter
