name: Default workflow
on:
  push:
    branches:
      - '*'
    paths-ignore:
    - 'main'
  pull_request:
    branches:
      - "*"
    paths-ignore:
    - 'main'

jobs:
  call-workflow:
    uses: anqa-ag/workflow-templates/.github/workflows/docker-pr.yml@main
    with:
      IMAGE_REPOSITORY: anqa-interface-pr
    secrets: inherit
       